### ISSUE TITLE
Checkpoint

### ISSUE THREAD

**Issue by danielrera** [CODINNLG/Bridge_Gap_Diffusion#2]
Thanks for your great work!

Can you also release trained checkpoints for other tasks like Story Generation or Text Simplification?

**Comment by PinzhengWang322** [comment]
I apologize for the delay in addressing this issue. I have updated the Text Simplification task. You can find the updated files [here](https://drive.google.com/drive/folders/1UvcN9mKOv-nVZuQpJaAOQWCG22sGk_2O?usp=sharing).
